baseURL = '/'
defaultContentLanguage = 'br'
defaultContentLanguageInSubdir = true
theme = 'enervoid'

[languages]
  [languages.br]
    contentDir = 'content/br'
    languageCode = 'pt-br'
    languageName = 'BR'
    title = 'Amaral Stack'
    weight = 1

    [languages.br.menus]
      [[languages.br.menus.main]]
        name = 'Blog'
        pageRef = '/blog'
        weight = 10

    [languages.br.params]
      avatar = "/perfil.jpg"

      [[languages.br.params.socials]]
        link = "https://github.com/leodramaral"
        icon = "devicon-github-original"
      [[languages.br.params.socials]]
        link = "https://www.linkedin.com/in/leodramaral/"
        icon = "devicon-linkedin-plain"

  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-us'
    languageName = 'EN'
    title = 'Amaral Stack'
    weight = 2

    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Blog'
        pageRef = '/blog'
        weight = 10

    [languages.en.params]
      avatar = "/perfil.jpg"

      [[languages.en.params.socials]]
        link = "https://github.com/leandroamaral"
        icon = "devicon-github-original"
      [[languages.en.params.socials]]
        link = "https://linkedin.com/in/leandroamaral"
        icon = "devicon-linkedin-plain"
      [[languages.en.params.socials]]
        link = "https://x.com/leandroamaral"
        icon = "devicon-twitter-original"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['$$','$$'], ['\\[','\\]']]
        inline = [['$','$'], ['\\(','\\)']]

    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[markup.highlight]
  noClasses = true
  codeFences = true
  guessSyntax = true
  lineNumbersInTable = true
  tabWidth = 4
  style = "monokai"
